### PR TITLE
Minor fixes and a new example

### PR DESCRIPTION
**Pull request by DavidHowlett**
We are using the sensor to read in the position of dials for a flight simulator based on X-Plane. I think  the tweaks to the library I made are helpful.

### CODE REVIEW

**Comment by sosandroid** [comment]
Thanks for your PR. I'll have a look asap.

**Comment by sosandroid** [comment]
Hi,

After looking at your PR, I'm not sure to understand why you want the chip address public. The only moment you need the chip address is at the constructor call. From that point, you don't need it anymore.

If you need to read the chip address during your program, a getter method is a better case as it avoids any unwanted address change.

Did I missed something ?

**Comment by DavidHowlett** [comment]
I was trying to set up an array of instances of the class, each with a different value of _chipAddress. 

After you questioned the way I solved the problem I did some googling and found out out how to pass in values to constructors when initialising an array of AMS_AS5048B. I have changed the code back to have a private chipAddress.

You did not miss anything. I just have rusty C++ knowledge.

**Comment by sosandroid** [comment]
Thanks for the homework :)

**Comment by sosandroid** [comment]
Hi @DavidHowlett 
I just updated the files to get a complete revision history.

In the xplane_dials.ino file an include or struct seems missing for 
`FlightSimFloat angles[NUM_SENSORS];`

**Comment by sosandroid** [comment]
An option is to make your example more generic such as below. What do you think ?

`#include <ams_as5048b.h>

// the constant U_DEG means the results are given in degrees
#define U_DEG 3

// declare an array of sensors
#define NUM_SENSORS 4
AMS_AS5048B sensors[NUM_SENSORS] = {AMS_AS5048B(0x40), AMS_AS5048B(0x41), AMS_AS5048B(0x42), AMS_AS5048B(0x43)};

double angles[NUM_SENSORS];
uint8_t AutoGain[NUM_SENSORS];

void setup() {
	//Start serial
	Serial.begin(9600);
	while (!Serial) ; //wait until Serial ready
	
	
	for(int i=0;i<NUM_SENSORS;i++){
		sensors[i].begin();
	}
}

void loop() {
	for(int i=0;i<NUM_SENSORS;i++){
		AutoGain[i] = sensors[i].getAutoGain();
		angles[i] = sensors[i].angleR(U_DEG,true);
	}
	serialOutput();

	delay (5);
}

void serialOutput () {
	for(int i=0;i<NUM_SENSORS;i++){
		Serial.print("Sensor ");
		Serial.print(i);
		Serial.print(" | auto gain: ");
		Serial.print(AutoGain[i]);
		Serial.print(" | angle: ");
		Serial.println(angles[i]);
	}
	Serial.println("--------");
}`

**Pull request merged**
